### ISSUE TITLE
Inventory insert isn't splitting ItemStack

### ISSUE THREAD

**Issue by this-is-envy** [Small-Loan-Studio/TGO#142]
it seems that we're not splitting item stacks correctly when adding and we need to overflow inventory slots.

**Comment by this-is-envy** [comment]
Gut here says it's something about resources having global scope / being shared instances similar to Unity ScriptableObjects (tbc: I'm not sure if this is even true in Godot / dependent on how we're creating the ItemStack).

But we also probably don't need ItemStack to be a resource - it could probably more correctly be a RefCounted object anyway.

TODO: does "RefCounted" opt us into any kind of garbage collection or do we still need to free these when they go out of scope?

**Comment by Sage-A** [comment]
![Image](https://github.com/user-attachments/assets/0dbc6656-9c17-4340-9f5d-0e0b0bf96dbd)
